server:
  servlet:
    context-path: /
  port: 9081
  compression:
    mime-types:
      - application/json

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fornecimento;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: user123
    password: pwd1234
    platform: h2
    continue-on-error: true

  application:
    name: fornecimento-ms
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: tech.ada.exemplos.salao.beleza.config.PagamentoFornecedorSerializer
      group-id: group_id
    
application:
  async:
    corePoolSize: 20
    maxPoolSize: 40
    queueCapacity: 60

  locale:
    country: BR
    language: pt

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - scheduledtasks
          - heapdump
          - mappings
          - env
          - flyway
          - configprops
          - shutdown
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      apache: WARN
    root: info
business:
  financeiro:
    url: ${VARIAVEL_URL:http://localhost:9080/pagamento/fornecedor}
    kafka:
      out: pagamento_fornecedor-topic